### ISSUE TITLE
Compatible with SM 2.45

### ISSUE THREAD

**Issue by RainerBielefeld** [lemon-juice/AMO-Browsing-for-SeaMonkey#9]
Please extend SM compatibility range to 2.45 due to my [test results](http://addonconverter.fotokraina.com/compatibility/#ext:AMO_Browsing_for_SeaMonkey).

**Comment by lemon-juice** [comment]
Okay, I will for the next version. You can also do it independently on AMO account - you can increase maxVersion of the extensions at any time without having to change the source code.

BTW, the AMO Browsing extension should not be on the [list](http://addonconverter.fotokraina.com/compatibility/) of extensions to convert. This is not a Firefox extension needing conversion. The converter will not help and can potentially break extensions that are specifically made for SeaMonkey.

**Comment by RainerBielefeld** [comment]
On 26.04.2016 13:54, lemon-juice wrote:

> BTW, the AMO Browsing extension should not be on the list

Hello,

may be, it's a problem that we do not have SeaMonkey-addon-compatibility 
information because Compatibility Reporter Addon does not work with 
SeaMonkey. So it Might be useful to add a "SM" tag for SeaMonkey 
specific add-ons, or indeed we should exclude SM-addons from that list 
and find a separate list (or may be user ratings might be sufficient?).

Currently I am tending to exclude SM-addons from your compatibility list.

CU

Rainer

**Comment by RainerBielefeld** [comment]
On 26.04.2016 13:54, lemon-juice wrote:

> BTW, the AMO Browsing extension should not be on the list

Hello,

I know, and I checked the differences. But looking into code tells me as 
much as looking into a newspaper in Mandarin language :-/

Regards

Rainer

**Comment by RainerBielefeld** [comment]
I modified Compatibility Range on AMO to 2.45.*, should be adapted in install.rdf

**Comment by lemon-juice** [comment]
Sometimes a SM extension is very old or not very well adapted to SM and then the converter may help so such extensions can be in the list (e.g. easyXdebug). However, this extension itself does not need the converter at all, that's why I think it would be misleading to put it there. In this case the converter only changed maxVersion so it does no harm. But maxVersion is does not need to be kept up to date because extensions with lower maxVersions will still work fine - only they may appear on AMO differently, but functionality is unaffected.

BTW, version 0.9.15 is waiting for full review now.
